spring:
  application:
    name: order-service

#config datasource
  datasource:
    url: jdbc:postgresql://localhost:5992/order_db
    username: order
    password: order
    driver-class-name: org.postgresql.Driver

# config for ddl
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9003