spring:
  application:
    name: product-service

# config datasource
  datasource:
    url: jdbc:postgresql://localhost:5991/product_db
    username: product
    password: product
    driver-class-name: org.postgresql.Driver

# config for ddl
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9002
